# What is the goal of your workflow
# Goal: Whenever someone changes the python code
# the linter will check if the syntax, indentation is correct or not
name: Auto Linter

on: 
  push:
    paths: "*.py"

jobs:
  code:
    runs-on: ubuntu-latest
    #This step will auto clone the code of the current branch into the runner
    steps:
      - name: Checkout the code
        uses: actions/checkout@v7
        #this step will install python
        - name: Set Up Python
          uses: actions/checkoutv7
          with:
            python-version: '3.13'
            
      - name: Install Linter
        run: pip install ruff
#This step will run the linter
      - name: Check the file for linting
        run: ruff check .
        
      
  
